sudo: false
language: php
php:
  - 5.4
  - 5.5
env:
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.1.1
    - MAGENTO_VERSION=magento-mirror-1.9.1.0
    - MAGENTO_VERSION=magento-mirror-1.9.0.1
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
branches:
  except:
    - /^\d+\.\d+\.\d+$/
addons:
  hosts:
    - magento.local
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  # Code Style
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 --report-width=180 ./app
  # Unit Tests
  - bash ./run_tests.sh
notifications:
  email:
    recipients: [ clemens.queissner@aoe.com ]
    on_failure: always
