<?php $fieldset = $this->getElement() ?>
<div class="rule-tree">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $fieldset->getLegend() ?></h4>
    </div>
    <fieldset id="<?php echo $fieldset->getHtmlId() ?>" <?php echo $fieldset->serialize(array('class')) ?>>
        <?php if ($fieldset->getComment()): ?>
            <p class="comment"><?php echo $this->escapeHtml($fieldset->getComment()) ?></p>
        <?php endif; ?>
        <?php echo $fieldset->getChildrenHtml() ?>
    </fieldset>
</div>
<script type="text/javascript">
    var <?php echo $fieldset->getHtmlId() ?> = new VarienRulesForm('<?php echo $fieldset->getHtmlId() ?>', '<?php echo $this->getNewChildUrl() ?>');
</script>
